//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `Sensor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ufro;

/** @hidden */
public class _SensorPrxI extends com.zeroc.Ice._ObjectPrxI implements SensorPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
